import type {
  Permisionario,
  Conductor,
  Vehiculo,
  Zona,
  Tarifa,
  Feriado,
  ConfiguracionNormativa,
  Deuda,
  Estacionamiento,
  Ticket,
  Pago,
} from './types';

export const SEED_TARIFA: Tarifa = {
  id: 'tarifa-1',
  autoHora: 700,
  motoHora: 300,
  descuentoDigital: 0.2,
  toleranciaMinutos: 5,
  fraccionamientoMinutos: 15,
  fraccionamientoDesdeHora: 2,
};

export const SEED_CONFIG: ConfiguracionNormativa = {
  horarioDiurnoInicio: '07:00',
  horarioDiurnoFinSemana: '21:00',
  horarioDiurnoFinSabado: '14:00',
  horarioNocturnoInicio: '22:00',
  horarioNocturnoFin: '05:00',
};

export const SEED_ZONAS: Zona[] = [
  {
    id: 'zona-centro',
    nombre: 'Centro',
    cuadras: ['Balcarce 400', 'España 400', 'Caseros 400', 'Mitre 300'],
    nocturnoHabilitado: false,
  },
  {
    id: 'zona-nocturna-1',
    nombre: 'Nocturna Norte',
    cuadras: ['Pellegrini 200', 'San Martín 500'],
    nocturnoHabilitado: true,
  },
];

export const SEED_FERIADOS: Feriado[] = [
  { id: 'feriado-1', fecha: '2026-07-09', descripcion: 'Día de la Independencia' },
  { id: 'feriado-2', fecha: '2026-05-25', descripcion: 'Día de la Patria' },
  { id: 'feriado-3', fecha: '2026-01-01', descripcion: 'Año Nuevo' },
];

export const SEED_PERMISIONARIOS: Permisionario[] = [
  {
    id: 'perm-1',
    nombre: 'Rosa',
    apellido: 'Martínez',
    legajo: 'P-0042',
    foto: '/avatars/perm1.svg',
    cuadraAsignada: 'Balcarce 400',
    zonaId: 'zona-centro',
    activo: true,
    horariosAutorizados: { diurno: true, nocturno: false },
    aliasMercadoPago: 'rosa.martinez.mp',
    createdAt: '2025-01-15T10:00:00.000Z',
  },
  {
    id: 'perm-2',
    nombre: 'Jorge',
    apellido: 'Pérez',
    legajo: 'P-0087',
    foto: '/avatars/perm2.svg',
    cuadraAsignada: 'España 400',
    zonaId: 'zona-centro',
    activo: true,
    horariosAutorizados: { diurno: true, nocturno: false },
    aliasMercadoPago: 'jorge.perez.mp',
    createdAt: '2025-02-20T10:00:00.000Z',
  },
  {
    id: 'perm-3',
    nombre: 'Ana',
    apellido: 'Rodríguez',
    legajo: 'P-0119',
    foto: '/avatars/perm3.svg',
    cuadraAsignada: 'Pellegrini 200',
    zonaId: 'zona-nocturna-1',
    activo: true,
    horariosAutorizados: { diurno: true, nocturno: true },
    aliasMercadoPago: 'ana.rodriguez.mp',
    createdAt: '2025-03-10T10:00:00.000Z',
  },
];

export const SEED_CONDUCTORES: Conductor[] = [
  {
    id: 'cond-1',
    nombre: 'Carlos Gómez',
    email: 'carlos@example.com',
    telefono: '387-4501234',
    dominioDefault: 'AB123CD',
    createdAt: '2026-04-01T10:00:00.000Z',
  },
  {
    id: 'cond-2',
    nombre: 'María López',
    email: 'maria@example.com',
    telefono: '387-4567890',
    dominioDefault: 'XYZ789',
    createdAt: '2026-04-15T10:00:00.000Z',
  },
  {
    id: 'cond-3',
    nombre: 'Lucía Fernández',
    email: 'lucia@example.com',
    telefono: '387-4598765',
    dominioDefault: 'GH456IJ',
    createdAt: '2026-04-20T10:00:00.000Z',
  },
];

export const SEED_VEHICULOS: Vehiculo[] = [
  { id: 'veh-1', dominio: 'AB123CD', tipo: 'auto', conductorId: 'cond-1' },
  { id: 'veh-2', dominio: 'XYZ789', tipo: 'auto', conductorId: 'cond-2' },
  { id: 'veh-3', dominio: 'GH456IJ', tipo: 'moto', conductorId: 'cond-3' },
  { id: 'veh-4', dominio: 'AA999BB', tipo: 'auto', conductorId: '' },
  { id: 'veh-5', dominio: 'CC555DD', tipo: 'moto', conductorId: '' },
  { id: 'veh-6', dominio: 'EE777FF', tipo: 'auto', conductorId: '' },
  { id: 'veh-7', dominio: 'GG333HH', tipo: 'auto', conductorId: '' },
  { id: 'veh-8', dominio: 'JJ888KK', tipo: 'moto', conductorId: '' },
  { id: 'veh-9', dominio: 'LL444MM', tipo: 'auto', conductorId: '' },
  { id: 'veh-10', dominio: 'PQR123', tipo: 'auto', conductorId: '' },
];

const now = new Date();
const fiveMinAgo = new Date(now.getTime() - 5 * 60000).toISOString();
const fifteenMinAgo = new Date(now.getTime() - 15 * 60000).toISOString();
const twentyMinAgo = new Date(now.getTime() - 20 * 60000).toISOString();
const thirtyFiveMinAgo = new Date(now.getTime() - 35 * 60000).toISOString();
const fortyMinAgo = new Date(now.getTime() - 40 * 60000).toISOString();
const fiftyMinAgo = new Date(now.getTime() - 50 * 60000).toISOString();
const fiftyFiveMinLater = new Date(now.getTime() + 55 * 60000).toISOString();
const fortyFiveMinLater = new Date(now.getTime() + 45 * 60000).toISOString();
const fortyMinLater = new Date(now.getTime() + 40 * 60000).toISOString();
const twentyFiveMinLater = new Date(now.getTime() + 25 * 60000).toISOString();
const fifteenMinLater = new Date(now.getTime() + 15 * 60000).toISOString();
const twentyMinLater = new Date(now.getTime() + 20 * 60000).toISOString();

export const SEED_ESTACIONAMIENTOS: Estacionamiento[] = [
  {
    id: 'est-1',
    dominio: 'AB123CD',
    tipo: 'auto',
    zonaId: 'zona-centro',
    cuadra: 'Balcarce 400',
    permisionarioId: 'perm-1',
    inicio: fifteenMinAgo,
    duracionMinutos: 60,
    metodoPago: 'digital',
    pagoId: 'pago-seed-1',
    activo: true,
    transferido: false,
  },
  {
    id: 'est-2',
    dominio: 'GH456IJ',
    tipo: 'moto',
    zonaId: 'zona-centro',
    cuadra: 'España 400',
    permisionarioId: 'perm-2',
    inicio: thirtyFiveMinAgo,
    duracionMinutos: 60,
    metodoPago: 'digital',
    pagoId: 'pago-seed-2',
    activo: true,
    transferido: false,
  },
  {
    id: 'est-3',
    dominio: 'AA999BB',
    tipo: 'auto',
    zonaId: 'zona-centro',
    cuadra: 'Balcarce 400',
    permisionarioId: 'perm-1',
    inicio: twentyMinAgo,
    duracionMinutos: 60,
    metodoPago: 'digital',
    pagoId: 'pago-seed-3',
    activo: true,
    transferido: false,
  },
  {
    id: 'est-4',
    dominio: 'CC555DD',
    tipo: 'moto',
    zonaId: 'zona-centro',
    cuadra: 'Balcarce 400',
    permisionarioId: 'perm-1',
    inicio: fiveMinAgo,
    duracionMinutos: 60,
    metodoPago: 'digital',
    pagoId: 'pago-seed-4',
    activo: true,
    transferido: false,
  },
  {
    id: 'est-5',
    dominio: 'EE777FF',
    tipo: 'auto',
    zonaId: 'zona-centro',
    cuadra: 'España 400',
    permisionarioId: 'perm-2',
    inicio: fortyMinAgo,
    duracionMinutos: 60,
    metodoPago: 'digital',
    pagoId: 'pago-seed-5',
    activo: true,
    transferido: false,
  },
  {
    id: 'est-6',
    dominio: 'GG333HH',
    tipo: 'auto',
    zonaId: 'zona-nocturna-1',
    cuadra: 'Pellegrini 200',
    permisionarioId: 'perm-3',
    inicio: twentyMinAgo,
    duracionMinutos: 60,
    metodoPago: 'digital',
    pagoId: 'pago-seed-6',
    activo: true,
    transferido: false,
  },
  {
    id: 'est-7',
    dominio: 'JJ888KK',
    tipo: 'moto',
    zonaId: 'zona-nocturna-1',
    cuadra: 'Pellegrini 200',
    permisionarioId: 'perm-3',
    inicio: fiftyMinAgo,
    duracionMinutos: 60,
    metodoPago: 'digital',
    pagoId: 'pago-seed-7',
    activo: true,
    transferido: false,
  },
  {
    id: 'est-8',
    dominio: 'LL444MM',
    tipo: 'auto',
    zonaId: 'zona-centro',
    cuadra: 'España 400',
    permisionarioId: 'perm-2',
    inicio: fifteenMinAgo,
    duracionMinutos: 60,
    metodoPago: 'digital',
    pagoId: 'pago-seed-8',
    activo: true,
    transferido: false,
  },
];

export const SEED_TICKETS: Ticket[] = [
  {
    id: 'ticket-1',
    numero: 'T-1001',
    dominio: 'AB123CD',
    tipo: 'auto',
    cuadra: 'Balcarce 400',
    permisionarioId: 'perm-1',
    inicio: fifteenMinAgo,
    duracionMinutos: 60,
    vencimiento: fortyFiveMinLater,
    monto: 560,
    metodoPago: 'digital',
    descuentoAplicado: true,
    activo: true,
    conductorId: 'cond-1',
  },
  {
    id: 'ticket-2',
    numero: 'T-1002',
    dominio: 'GH456IJ',
    tipo: 'moto',
    cuadra: 'España 400',
    permisionarioId: 'perm-2',
    inicio: thirtyFiveMinAgo,
    duracionMinutos: 60,
    vencimiento: twentyFiveMinLater,
    monto: 240,
    metodoPago: 'digital',
    descuentoAplicado: true,
    activo: true,
    conductorId: 'cond-3',
  },
  {
    id: 'ticket-3',
    numero: 'T-1003',
    dominio: 'AA999BB',
    tipo: 'auto',
    cuadra: 'Balcarce 400',
    permisionarioId: 'perm-1',
    inicio: twentyMinAgo,
    duracionMinutos: 60,
    vencimiento: fortyMinLater,
    monto: 560,
    metodoPago: 'digital',
    descuentoAplicado: true,
    activo: true,
    conductorId: '',
  },
  {
    id: 'ticket-4',
    numero: 'T-1004',
    dominio: 'CC555DD',
    tipo: 'moto',
    cuadra: 'Balcarce 400',
    permisionarioId: 'perm-1',
    inicio: fiveMinAgo,
    duracionMinutos: 60,
    vencimiento: fiftyFiveMinLater,
    monto: 240,
    metodoPago: 'digital',
    descuentoAplicado: true,
    activo: true,
    conductorId: '',
  },
  {
    id: 'ticket-5',
    numero: 'T-1005',
    dominio: 'EE777FF',
    tipo: 'auto',
    cuadra: 'España 400',
    permisionarioId: 'perm-2',
    inicio: fortyMinAgo,
    duracionMinutos: 60,
    vencimiento: twentyMinLater,
    monto: 560,
    metodoPago: 'digital',
    descuentoAplicado: true,
    activo: true,
    conductorId: '',
  },
  {
    id: 'ticket-6',
    numero: 'T-1006',
    dominio: 'GG333HH',
    tipo: 'auto',
    cuadra: 'Pellegrini 200',
    permisionarioId: 'perm-3',
    inicio: twentyMinAgo,
    duracionMinutos: 60,
    vencimiento: fortyMinLater,
    monto: 560,
    metodoPago: 'digital',
    descuentoAplicado: true,
    activo: true,
    conductorId: '',
  },
  {
    id: 'ticket-7',
    numero: 'T-1007',
    dominio: 'JJ888KK',
    tipo: 'moto',
    cuadra: 'Pellegrini 200',
    permisionarioId: 'perm-3',
    inicio: fiftyMinAgo,
    duracionMinutos: 60,
    vencimiento: fifteenMinLater,
    monto: 240,
    metodoPago: 'digital',
    descuentoAplicado: true,
    activo: true,
    conductorId: '',
  },
  {
    id: 'ticket-8',
    numero: 'T-1008',
    dominio: 'LL444MM',
    tipo: 'auto',
    cuadra: 'España 400',
    permisionarioId: 'perm-2',
    inicio: fifteenMinAgo,
    duracionMinutos: 60,
    vencimiento: fortyFiveMinLater,
    monto: 560,
    metodoPago: 'digital',
    descuentoAplicado: true,
    activo: true,
    conductorId: '',
  },
];

export const SEED_PAGOS: Pago[] = [
  {
    id: 'pago-seed-1',
    estacionamientoId: 'est-1',
    ticketId: 'ticket-1',
    dominio: 'AB123CD',
    monto: 560,
    metodoPago: 'digital',
    estado: 'success',
    permisionarioId: 'perm-1',
    cuadra: 'Balcarce 400',
    conductorId: 'cond-1',
    createdAt: fifteenMinAgo,
  },
  {
    id: 'pago-seed-2',
    estacionamientoId: 'est-2',
    ticketId: 'ticket-2',
    dominio: 'GH456IJ',
    monto: 240,
    metodoPago: 'digital',
    estado: 'success',
    permisionarioId: 'perm-2',
    cuadra: 'España 400',
    conductorId: 'cond-3',
    createdAt: thirtyFiveMinAgo,
  },
  {
    id: 'pago-seed-3',
    estacionamientoId: 'est-3',
    ticketId: 'ticket-3',
    dominio: 'AA999BB',
    monto: 560,
    metodoPago: 'digital',
    estado: 'success',
    permisionarioId: 'perm-1',
    cuadra: 'Balcarce 400',
    conductorId: '',
    createdAt: twentyMinAgo,
  },
  {
    id: 'pago-seed-4',
    estacionamientoId: 'est-4',
    ticketId: 'ticket-4',
    dominio: 'CC555DD',
    monto: 240,
    metodoPago: 'digital',
    estado: 'success',
    permisionarioId: 'perm-1',
    cuadra: 'Balcarce 400',
    conductorId: '',
    createdAt: fiveMinAgo,
  },
  {
    id: 'pago-seed-5',
    estacionamientoId: 'est-5',
    ticketId: 'ticket-5',
    dominio: 'EE777FF',
    monto: 560,
    metodoPago: 'digital',
    estado: 'success',
    permisionarioId: 'perm-2',
    cuadra: 'España 400',
    conductorId: '',
    createdAt: fortyMinAgo,
  },
  {
    id: 'pago-seed-6',
    estacionamientoId: 'est-6',
    ticketId: 'ticket-6',
    dominio: 'GG333HH',
    monto: 560,
    metodoPago: 'digital',
    estado: 'success',
    permisionarioId: 'perm-3',
    cuadra: 'Pellegrini 200',
    conductorId: '',
    createdAt: twentyMinAgo,
  },
  {
    id: 'pago-seed-7',
    estacionamientoId: 'est-7',
    ticketId: 'ticket-7',
    dominio: 'JJ888KK',
    monto: 240,
    metodoPago: 'digital',
    estado: 'success',
    permisionarioId: 'perm-3',
    cuadra: 'Pellegrini 200',
    conductorId: '',
    createdAt: fiftyMinAgo,
  },
  {
    id: 'pago-seed-8',
    estacionamientoId: 'est-8',
    ticketId: 'ticket-8',
    dominio: 'LL444MM',
    monto: 560,
    metodoPago: 'digital',
    estado: 'success',
    permisionarioId: 'perm-2',
    cuadra: 'España 400',
    conductorId: '',
    createdAt: fifteenMinAgo,
  },
];

export const SEED_DEUDAS: Deuda[] = [
  {
    id: 'deuda-1',
    dominio: 'XYZ789',
    cuadra: 'Balcarce 400',
    permisionarioId: 'perm-1',
    monto: 700,
    fecha: '2026-05-20T14:30:00.000Z',
    estado: 'pendiente',
    tipo: 'incumplimiento',
  },
  {
    id: 'deuda-2',
    dominio: 'PQR123',
    cuadra: 'España 400',
    permisionarioId: 'perm-2',
    monto: 700,
    fecha: '2026-05-22T09:15:00.000Z',
    estado: 'pendiente',
    tipo: 'incumplimiento',
  },
  {
    id: 'deuda-3',
    dominio: 'GH456IJ',
    cuadra: 'Pellegrini 200',
    permisionarioId: 'perm-3',
    monto: 900,
    fecha: '2026-05-25T23:15:00.000Z',
    estado: 'pendiente',
    tipo: 'hora_extra',
    minutosExcedidos: 60,
    vencimientoOriginal: '2026-05-25T22:00:00.000Z',
  },
  {
    id: 'deuda-4',
    dominio: 'MM222NN',
    cuadra: 'Balcarce 400',
    permisionarioId: 'perm-1',
    monto: 700,
    fecha: new Date(now.getTime() - 2 * 3600000).toISOString(),
    estado: 'pendiente',
    tipo: 'incumplimiento',
  },
  {
    id: 'deuda-5',
    dominio: 'PP666QQ',
    cuadra: 'España 400',
    permisionarioId: 'perm-2',
    monto: 300,
    fecha: new Date(now.getTime() - 4 * 3600000).toISOString(),
    estado: 'pendiente',
    tipo: 'hora_extra',
    minutosExcedidos: 30,
    vencimientoOriginal: new Date(now.getTime() - 5 * 3600000).toISOString(),
  },
  {
    id: 'deuda-6',
    dominio: 'RR999SS',
    cuadra: 'Pellegrini 200',
    permisionarioId: 'perm-3',
    monto: 700,
    fecha: new Date(now.getTime() - 1 * 3600000).toISOString(),
    estado: 'pendiente',
    tipo: 'incumplimiento',
  },
];

export const SEED_GEOLOCALIZACION: Record<string, { lat: number; lng: number }> = {
  'Balcarce 400': { lat: -24.7847, lng: -65.4116 },
  'España 400': { lat: -24.7862, lng: -65.4103 },
  'Caseros 400': { lat: -24.7838, lng: -65.4095 },
  'Mitre 300': { lat: -24.7872, lng: -65.4128 },
  'Pellegrini 200': { lat: -24.7815, lng: -65.4087 },
  'San Martín 500': { lat: -24.7851, lng: -65.4072 },
};
